const RSDiff = require("rs-diff");

const items1 = [
  {
    msgid: "TODO List",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["TODO List"],
    comments: [],
    extractedComments: ["Please don't change the name of the application"],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Enter your credentials below to login",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Entrez vos identifiants ci-dessous pour vous connecter"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Login successful !\nWelcome back %s !",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Connexion réussie !\nBon retour %s !"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Make sure you've entered the correct username and password",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Assurez-vous que vous avez entré le nom d'utilisateur correct et le mot de passe",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "I forgot my password",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["J'ai oublié mon mot de passe"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid:
      "Enter your address in the field below. A new password will be sent to your inbox.",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Entrez votre adresse dans le champ ci-dessous. Un nouveau mot de passe sera envoyé à votre boîte de réception.",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Sign up for free! No credit card required!",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Inscrivez-vous gratuitement ! Aucune carte de crédit !"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid:
      "Thank you for signing up !\n" +
      "Please check your email address to activate your account.",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Je vous remercie pour vous inscrire !\n" +
        "Veuillez vérifier votre adresse e-mail pour activer votre compte.",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "We were unable to sign you up.\nPlease correct the marked fields.",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Nous n'avons pas pu vous inscrire.\n" +
        "Veuillez corriger les champs marqués.",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Terms and conditions",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Termes et conditions"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Just one user online",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: "There are %d users online",
    msgstr: ["Un seul utilisateur en ligne", "Il y a %d utilisateurs en ligne"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Password",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Mot de passe"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
];
const items2 = [
  {
    msgid: "TODO List",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["TODO List"],
    comments: [],
    extractedComments: ["Please don't change the name of the application"],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Enter your credentials below to login",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Entrez vos identifiants ci-dessous pour vous connecter"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Login successful !\nWelcome back %s !",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Connexion réussie !\nBon retour %s !"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Make sure you've entered the correct username and password",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Assurez-vous que vous avez entré le nom d'utilisateur correct et le mot de passe",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "I forgot my password",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["J'ai oublié mon mot de passe"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid:
      "Enter your address in the field below. A new password will be sent to your inbox.",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Entrez votre adresse dans le champ ci-dessous. Un nouveau mot de passe sera envoyé à votre boîte de réception.",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Sign up for free! No credit card required!",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Inscrivez-vous gratuitement ! Aucune carte de crédit !"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid:
      "Thank you for signing up !\n" +
      "Please check your email address to activate your account.",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Je vous remercie pour vous inscrire !\n" +
        "Veuillez vérifier votre adresse e-mail pour activer votre compte.",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "We were unable to sign you up.\nPlease correct the marked fields.",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: [
      "Nous n'avons pas pu vous inscrire.\n" +
        "Veuillez corriger les champs marqués.",
    ],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Terms and conditions",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Termes et conditions"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Just one user online",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: "There are %d users online",
    msgstr: ["Un seul utilisateur en ligne", "Il y a %d utilisateurs en ligne"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
  {
    msgid: "Password",
    msgctxt: null,
    references: ["/app/modules/views"],
    msgid_plural: null,
    msgstr: ["Mot de passe"],
    comments: [],
    extractedComments: [],
    flags: {},
    obsolete: false,
    nplurals: 2,
  },
];

const result = RSDiff(items1, items2);
console.log(result);
